### ISSUE TITLE
The summary part is missing

### ISSUE THREAD

**Issue by alv2017** [Evelina2022/Multiplication_for_Kids#1]
The summary part is described in Week02 homework, Assignment 2

https://github.com/lajm-programming/introduction-to-python-2023/blob/main/Week02/Week02_Homework.md

**Comment by alv2017** [comment]
I found the solution in https://github.com/Evelina2022/Week02PythonHomework

**Comment by Evelina2022** [comment]
ar viskas gerai, nes nebesupratau ?

**Comment by alv2017** [comment]
su sia dalimi viskas tvarkoj
